echo steam_applist : *ISteamAppList; > steam_applist.jai
echo steam_apps : *ISteamApps; > steam_apps.jai
echo steam_controller : *ISteamController; > steam_controller.jai
echo steam_friends : *ISteamFriends; > steam_friends.jai
echo steam_gamesearch : *ISteamGameSearch; > steam_gamesearch.jai
echo steam_gameserver : *ISteamGameServer; > steam_gameserver.jai
echo steam_gameserverapps : *ISteamApps; > steam_gameserverapps.jai
echo steam_gameserverhttp : *ISteamHTTP; > steam_gameserverhttp.jai
echo steam_gameserverinventory : *ISteamInventory; > steam_gameserverinventory.jai
echo steam_gameservernetworking : *ISteamNetworking; > steam_gameservernetworking.jai
echo steam_gameservernetworkingmessages : *ISteamNetworkingMessages; > steam_gameservernetworkingmessages.jai
echo steam_gameservernetworkingsockets : *ISteamNetworkingSockets; > steam_gameservernetworkingsockets.jai
echo steam_gameserverstats : *ISteamGameServerStats; > steam_gameserverstats.jai
echo steam_gameserverugc : *ISteamUGC; > steam_gameserverugc.jai
echo steam_gameserverutils : *ISteamUtils; > steam_gameserverutils.jai
echo steam_htmlsurface : *ISteamHTMLSurface; > steam_htmlsurface.jai
echo steam_http : *ISteamHTTP; > steam_http.jai
echo steam_input : *ISteamInput; > steam_input.jai
echo steam_inventory : *ISteamInventory; > steam_inventory.jai
echo steam_matchmaking : *ISteamMatchmaking; > steam_matchmaking.jai
echo steam_matchmakingservers : *ISteamMatchmakingServers; > steam_matchmakingservers.jai
echo steam_music : *ISteamMusic; > steam_music.jai
echo steam_musicremote : *ISteamMusicRemote; > steam_musicremote.jai
echo steam_networking : *ISteamNetworking; > steam_networking.jai
echo steam_networkingmessages : *ISteamNetworkingMessages; > steam_networkingmessages.jai
echo steam_networkingsockets : *ISteamNetworkingSockets; > steam_networkingsockets.jai
echo steam_networkingutils : *ISteamNetworkingUtils; > steam_networkingutils.jai
echo steam_parentalsettings : *ISteamParentalSettings; > steam_parentalsettings.jai
echo steam_parties : *ISteamParties; > steam_parties.jai
echo steam_remoteplay : *ISteamRemotePlay; > steam_remoteplay.jai
echo steam_remotestorage : *ISteamRemoteStorage; > steam_remotestorage.jai
echo steam_screenshots : *ISteamScreenshots; > steam_screenshots.jai
echo steam_ugc : *ISteamUGC; > steam_ugc.jai
echo steam_user : *ISteamUser; > steam_user.jai
echo steam_userstats : *ISteamUserStats; > steam_userstats.jai
echo steam_utils : *ISteamUtils; > steam_utils.jai
echo steam_video : *ISteamVideo; > steam_video.jai
